# Configurações do Banco de Dados (SQLite) via Variáveis de Ambiente
spring.datasource.url=${DB_URL:jdbc:sqlite:kodexia.db}
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA e Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Configurações do Servidor
server.port=${PORT:8080}

# Segurança (JWT Secret extraído via env para não expor a chave)
jwt.secret=${JWT_SECRET:super_secret_default_key_change_in_prod}