server.port=8080

# Configuração do SQLite
spring.datasource.url=jdbc:sqlite:kodexia.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Dialeto do Hibernate para SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Atualiza o esquema do banco de dados automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL gerado no log
spring.jpa.show-sql=true