# Como usar o Banco de Dados Fisico (H2 em arquivo):
# Copie essas linhas para o seu application.properties principal quando quiser ativar:

server.port=8080
spring.datasource.url=jdbc:h2:file:./data/kodexiadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
